PULP_APP = test
PULP_APP_C_SRCS = \
	main.c \
	tests/test_pixel.c \
	tests/test_line.c \
	tests/test_kotak.c \
	tests/test_tangga.c \
	tests/test_papancatur.c \
	tests/test_text.c \
	tests/test_circle.c \
	font/font5x7.c \
	oled.c

PULP_CFLAGS = -O3 -g

include $(PULPRT_HOME)/rules/pulp.mk

