PULP_APP        = test
PULP_APP_C_SRCS = test.c \
                  ntp_sync.c \
                  ../../sensors/DS1307/rtc.c

PULP_CFLAGS     = -O3 -g \
                  -I../../sensors/DS1307

include $(PULPRT_HOME)/rules/pulp.mk
