PULP_APP        = test
PULP_APP_C_SRCS = test.c \
                  step_counter.c \
                  ../../sensors/mpu6050/mpu6050.c \
                  ../../sensors/DS1307/rtc.c

PULP_CFLAGS     = -O3 -g \
                  -I../../sensors/mpu6050 \
                  -I../../sensors/DS1307

include $(PULPRT_HOME)/rules/pulp.mk